name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Build Parameters
        uses: JustSiHeshteger/pipeline-action@08520c1f416e9d189211e7e99fc6a5750552acf5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@08520c1f416e9d189211e7e99fc6a5750552acf5

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@08520c1f416e9d189211e7e99fc6a5750552acf5

  integrationTest:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@08520c1f416e9d189211e7e99fc6a5750552acf5

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [build, test, integrationTest]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@08520c1f416e9d189211e7e99fc6a5750552acf5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [build, test, integrationTest, sonar]
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@08520c1f416e9d189211e7e99fc6a5750552acf5