name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTOR: 'temurin'
  WORKING_DIRECTORY: '.'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@1c8c147ef783fef2ff788b6abda521e85a3f21be

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@1c8c147ef783fef2ff788b6abda521e85a3f21be

  integrationTest:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@1c8c147ef783fef2ff788b6abda521e85a3f21be

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [test, integrationTest]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@1c8c147ef783fef2ff788b6abda521e85a3f21be
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerBuild:
    name: Docker Build App
    runs-on: ubuntu-latest
    needs: [sonar]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker Build Run
        uses: JustSiHeshteger/pipeline-action/docker-build@1c8c147ef783fef2ff788b6abda521e85a3f21be

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [dockerBuild]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@1c8c147ef783fef2ff788b6abda521e85a3f21be