name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Build Parameters
        uses: JustSiHeshteger/pipeline-action/echo-app-parameters@2c4a13d2d1b713d98121209e31e167f1d8539170
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@2c4a13d2d1b713d98121209e31e167f1d8539170

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@2c4a13d2d1b713d98121209e31e167f1d8539170

  integrationTest:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@2c4a13d2d1b713d98121209e31e167f1d8539170

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [test, integrationTest]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@2c4a13d2d1b713d98121209e31e167f1d8539170
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerBuild:
    name: Docker Build App
    runs-on: ubuntu-latest
    needs: [sonar]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker Build Run
        uses: JustSiHeshteger/pipeline-action/docker-build@2c4a13d2d1b713d98121209e31e167f1d8539170

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [dockerBuild]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@2c4a13d2d1b713d98121209e31e167f1d8539170