name: CI/CD Gradle

on:
  push:
    branches:
      - master
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTOR: 'zulu'
  WORKING_DIRECTORY: '.'
  ARTIFACT_NAME: 'artifact'
  DOCKER_BASE_IMAGE: eclipse-temurin:21-jre-alpine

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.app.outputs.app-name }}
      app-version: ${{ steps.app.outputs.app-version }}
      jar-name: ${{ steps.app.outputs.jar-name }}

    steps:
      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}

      - name: Resolve JAR_NAME from Gradle
        id: app
        run: |
          APP_NAME=$(./gradlew -q printAppName)
          APP_VERSION=$(./gradlew -q printAppVersion)
          JAR_NAME=$(./gradlew -q printJarName)
      
          echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "app-version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "jar-name=$JAR_NAME" >> $GITHUB_OUTPUT

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  integration-test:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  publish-artifact:
    name: Publish Build Artifact
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Publish Artifact
        uses: JustSiHeshteger/pipeline-action/publish-artifact@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          application-name: ${{ needs.build.outputs.jar-name }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          working-directory: ${{ env.WORKING_DIRECTORY }}

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [test, integration-test]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    name: Docker Build App
    runs-on: ubuntu-latest
    needs: [build, sonar, publish-artifact]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker Build Run
        uses: JustSiHeshteger/pipeline-action/docker-build@004934fbb4e1594a23c15489efc695c17a1d701e
        with:
          base-image: ${{ env.DOCKER_BASE_IMAGE }}
          image-name: ${{ needs.build.outputs.app-name }}
          image-tag: ${{ needs.build.outputs.app-version }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          working-directory: ${{ env.WORKING_DIRECTORY }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@004934fbb4e1594a23c15489efc695c17a1d701e