name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTOR: 'zulu'
  WORKING_DIRECTORY: '.'
  ARTIFACT_NAME: 'artifact'
  IMAGE_TAG: 'latest'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    outputs:
      jar-name: ${{ steps.app.outputs.jar-name }}
    steps:
      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@v2.14.11
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
          artifact-name: ${{ env.ARTIFACT_NAME }}

      - name: Resolve JAR_NAME from Gradle
        id: app
        run: |
          JAR_NAME=$(./gradlew -q printAppName)
          echo "jar-name=JAR_NAME" >> $GITHUB_OUTPUT

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@v2.14.11
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  integration-test:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@v2.14.11
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  publish-artifact:
    name: Publish Build Artifact
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Publish Artifact
        uses: JustSiHeshteger/pipeline-action/publish-artifact@v2.14.11
        with:
          application-name: ${{ needs.build.outputs.jar-name }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          working-directory: ${{ env.WORKING_DIRECTORY }}

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [test, integration-test]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@v2.14.11
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build:
    name: Docker Build App
    runs-on: ubuntu-latest
    needs: [sonar, publish-artifact]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker Build Run
        uses: JustSiHeshteger/pipeline-action/docker-build@v2.14.11
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
          image-name: ${{ env.IMAGE_NAME }}
          image-tag: ${{ env.IMAGE_TAG }}
          artifact-name: ${{ env.ARTIFACT_NAME }}
          working-directory: ${{ env.WORKING_DIRECTORY }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@v2.14.11