name: CI/CD Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRIBUTOR: 'zulu'
  WORKING_DIRECTORY: '.'

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        uses: JustSiHeshteger/pipeline-action/build@7f99f27d0b147daf2940b5b0941e1bea650fcaf7
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  test:
    name: Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Test
        uses: JustSiHeshteger/pipeline-action/test@7f99f27d0b147daf2940b5b0941e1bea650fcaf7
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  integrationTest:
    name: Integration Test App
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run Integration Test
        uses: JustSiHeshteger/pipeline-action/integration-test@7f99f27d0b147daf2940b5b0941e1bea650fcaf7
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}

  sonar:
    name: SonarCloud Analyze
    runs-on: ubuntu-latest
    needs: [test, integrationTest]
    steps:
      - name: Sonar Run
        uses: JustSiHeshteger/pipeline-action/sonar@7f99f27d0b147daf2940b5b0941e1bea650fcaf7
        with:
          java-version: ${{ env.JAVA_VERSION }}
          java-distributor: ${{ env.JAVA_DISTRIBUTOR }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerBuild:
    name: Docker Build App
    runs-on: ubuntu-latest
    needs: [sonar]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Docker Build Run
        uses: JustSiHeshteger/pipeline-action/docker-build@7f99f27d0b147daf2940b5b0941e1bea650fcaf7

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: [dockerBuild]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Run Deploy
        uses: JustSiHeshteger/pipeline-action/deploy@7f99f27d0b147daf2940b5b0941e1bea650fcaf7